import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-white text-black">
        <div className="container flex flex-col gap-4 px-16 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            {'Hi, I\'m '}<span className="text-emerald-400">{'Alex'}</span>
          </h1>
          <h2 className="text-4xl font-extrabold">
            Projects
          </h2>
          <div className="grid grid-cols-1 gap-4 md:gap-8">
            <div className="flex flex-row w-full gap-4">
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl p-4 bg-emerald-400 hover:bg-opacity-40"
                href="https://amillionlagers.com"
              >
                <h3 className="text-2xl font-bold">amillionlagers.com</h3>
                <div className="text-lg">
                  Just the basics - Everything you need to know to set up your
                  database and authentication.
                </div>
              </Link>
              <div>
                <h3 className="text-2xl font-bold">A Million Lagers</h3>
                <p>A fullstack web application designed, created, and deployed by myself.</p>
                <p>Technologies include Next.js, tRPC, Prisma, Tailwindcss, Clerk.dev, MySQL.</p>
                <p>Currently has an active userbase of ~40 people</p>
              </div>
            </div>
            <div>
              <div className="flex flex-row w-full gap-4">
                <Link
                  className="flex max-w-xs flex-col gap-4 rounded-xl p-4 bg-emerald-400 hover:bg-opacity-40"
                  href="https://create.t3.gg/en/introduction"
                  target="_blank"
                >
                  <h3 className="text-2xl font-bold">To-do</h3>
                  <div className="text-lg">
                    Learn more about Create T3 App, the libraries it uses, and how
                    to deploy it.
                  </div>
                </Link>
                <div>
                  <h3 className="text-2xl font-bold">Task List</h3>
                  <p>A fullstack web application designed, created, and deployed by myself.</p>
                  <p>Technologies include Next.js, tRPC, Prisma, Tailwindcss, Clerk.dev, MySQL.</p>
                  <p>Currently has an active userbase of ~40 people</p>
                </div>
              </div>
            </div>
            <div>
              <div className="flex flex-row w-full gap-4">
                <Link
                  className="flex max-w-xs flex-col gap-4 rounded-xl p-4 bg-emerald-400 hover:bg-opacity-40"
                  href="https://create.t3.gg/en/introduction"
                  target="_blank"
                >
                  <h3 className="text-2xl font-bold">Polyrhythm Visualisation</h3>
                  <div className="text-lg">
                    Learn more about Create T3 App, the libraries it uses, and how
                    to deploy it.
                  </div>
                </Link>
                <div>
                  <h3 className="text-2xl font-bold">Task List</h3>
                  <p>A fullstack web application designed, created, and deployed by myself.</p>
                  <p>Technologies include Next.js, tRPC, Prisma, Tailwindcss, Clerk.dev, MySQL.</p>
                  <p>Currently has an active userbase of ~40 people</p>
                </div>
              </div>
            </div>
          </div>
          <div>
            <h3 className="text-2xl font-bold">Contact Info</h3>
            <div className="flex flex-row gap-4">
              <div>Email</div>
              <div>Github</div>
              <div>LinkedIn</div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
